module.exports = {
    name: 'quote',
    description: 'Envia quotes',
    execute(message, args) {
        const quotesArray = [
            '"Zute!" \n — Dores',
            '"Vocês têm de expandir os horizontes." \n — Ção',
            '"Quem carrega no giz tem personalidade forte." \n — Ção',
            '"oh" \n — rudrigu',
            '"Grande dia" \n — Gonçalo Cuesta',
            '"ora" \n — Miguel Marinha',
            '"Excelente!!" \n — Domingos',
            '"Têm de ouvir o silêncio" \n — Ção',
            '"Oficialmente boa tarde a todos." \n — Mendonça',
            '"é um ponto." \n — Cláudio',
            '"Perfectly balanced, as all things should be." \n — Thanos',
            `"Just because you're correct doesn't meant you're right." \n — Fate/stay night`,
            `"People die when they are killed." \n — Fate/stay night`,
            '"nice" \n — Quartin',
            '"acontece" \n — rudrigu',
            '"Fine I’ll do it myself." \n — Thanos',
            '"Asinceramente" \n — Bruno',
            '"Hmmmm" \n — todos neste servidor',
            '"Punaise!" \n — Dores',
            '"You are 100% gay" \n — Dank Memer',
            '"Isto está estrategicamente posicionado" \n — Ção',
            '"a minha consideração por ti diminuiu" \n — russo',
            '"Magnífico" \n — Mágico Pereira',
            '"faaaaaaacil" \n — claudio',
            '"Você é o Donald Trump" \n — Professora de Filosofia',
            '"Mas tipo, deficientes no bom sentido." \n — zequinha',
            '"A op de domestic na kanojo é horrível" \n — nobody',
            '"🍞" \n — Quartin',
            '"Os bissexuais são o par perfeito para os travestis" \n — Bruno',
            '"Sempre que alguém faz um Haiku espontâneo, o que a pessoa diz é necessariamente verdade." \n — Verdade Universal',
            '"O truck-kun pode ser invocado em qualquer lado" \n — Verdade (quase) Universal',
            '"Fodeste qualquer coisa? Eish és ganda tono. Toma lá fita cola preta" \n — Dica',
            '"Sou contra o waifu bot." \n — Miguel Marinha',
            '"Isto ativa certas partes do cérebro." \n — Ção',
            '"ara ara" \n — waifus',
            '"nossa senhora mano" \n — Rui',
            '"Com classe!" \n — Domingos',
            '"tru" \n — rudrigu',
            '"💛" \n — HaikuBot',
            '"Não tens permissões suficientes." \n — RudriguBot',
            '"hora de simpar" \n — rudrigu',
            '"Ser simp ou não ser simp, eis a questão." \n — William Shakespeare',
            '"||Toda a gente lê os spoilers||" \n — ||Verdade Universal||',
            '"Aßßßßßßßßßßßß" \n — Bruno',
            '"nimporta" \n — Miguel Marinha',
            '"é a bida" \n — todos neste servidor',
            '"Tens ratolas em casa. Bota langonha nessa merda.\nO que é que acontece ao ratolas? Sem abrigo, foda-se. Fodeste a vida ao rato." \n — Dica',
            '"hj em dia..." \n — rodrigo montiero',
            '"antigamente..." \n — rodrigo montiero',
            '"tem de ser" \n — rudrigu',
            '"a vida é cruel" \n — verdade universal?',
            '"vou fazer torradas" \n — exemplo de uma boa ação',
            '"Relógio dáora" \n — Miguel Marinha, 8ºano',
            '"um dia..." \n — rodrigo montiero',
            '"a vida é como uma peneira" \n — rodrigo montiero',
            '"quando a revolução chegar..." \n — Miguel Marinha',
            '"Waifu is Laifu" \n — Verdade Universal',
            '"Relógio dáora" \n — Miguel Marinha',
            '"gaaaaaaaanda cena" \n — Rodrigo Santos',
            '"Passa para cá o relógio, isto é um assalto!" \n — Quartin, no Brasil',
            '"Foi o meu subconsciente" \n — Ção',
            '"Paridade nada tem haver com parir" \n — Ção'
        ]

        const randomQuote = quotesArray[Math.floor(Math.random() * quotesArray.length)]
        message.channel.send(randomQuote)
    },
}